### ISSUE TITLE
API Access Forbidden

### ISSUE THREAD

**Issue by ziimakc** [sanzodown/poe-item-checker#1]
Currently it's not working :(

```
// https://poe-item-checker.vercel.app/api/poe/search 403
{
    "error": "API Access Forbidden",
    "details": "The PoE Trade API is currently blocking requests from this service. Please try using the official trade site directly."
}
```

**Comment by Nokami93** [comment]
An alternative would be to run the application yourself, that was the initial push here on GitHub before he basically redirected it all to the website. But Sidekick is now working for PoE2, so demand will probably decrease for manually copying items. But overall this worked really great for the time being. Thanks to the creator!

**Comment by sanzodown** [comment]
Hi! The app is getting blocked by PoE's API because it's hosted on Vercel's free tier with shared IPs. While I could fix this by moving to a paid host with dedicated IPs, I don't want to spend money for a free tool.
Maybe i'll be unblocked from GGG but idk when.

> An alternative would be to run the application yourself, that was the initial push here on GitHub before he basically redirected it all to the website. But Sidekick is now working for PoE2, so demand will probably decrease for manually copying items. But overall this worked really great for the time being. Thanks to the creator!

Thanks for this comment! You're totally right - this was meant to be self-hosted and that's still the best way to use it. With Sidekick now supporting PoE2 it is a way better tool than mine and u should use it.
Sidekick : https://sidekick-poe.github.io/

### For Users who still want to use it
1. Clone the repo
2. Run it locally (`pnpm install && pnpm dev`)
3. Access through `localhost:3000`

You'll be using your own IP and everything will work fine!
